clinica/urls.py
from django.urls import path
from .views import (
    Home,
    CadastrarPacientes,
    CadastrarProfissionais,
    CadastrarTransacoes,
    CadastrarAgendamentos,
    ListarPacientes,
    ListarProfissionais,
    ListarTransacoes,
    ListarAgendamentos,
    EditarPaciente,
    EditarProfissional,
    EditarTransacao,
    EditarAgendamento,
    delete,
)

app_name = "clinica"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path(
        "cadastrar-pacientes/", CadastrarPacientes.as_view(), name="cadastrar_pacientes"
    ),
    path(
        "cadastrar-profissionais/",
        CadastrarProfissionais.as_view(),
        name="cadastrar_profissionais",
    ),
    path(
        "cadastrar-transacoes/",
        CadastrarTransacoes.as_view(),
        name="cadastrar_transacoes",
    ),
    path(
        "cadastrar-agendamentos/",
        CadastrarAgendamentos.as_view(),
        name="cadastrar_agendamentos",
    ),
    path("listar-pacientes/", ListarPacientes.as_view(), name="listar_pacientes"),
    path(
        "listar-profissionais/",
        ListarProfissionais.as_view(),
        name="listar_profissionais",
    ),
    path("listar-transacoes/", ListarTransacoes.as_view(), name="listar_transacoes"),
    path(
        "listar-agendamentos/", ListarAgendamentos.as_view(), name="listar_agendamentos"
    ),
    path("editar/<int:pk>", EditarPaciente.as_view(), name="editar_paciente"),
    path(
        "editar-profissional/<int:pk>",
        EditarProfissional.as_view(),
        name="editar_profissional",
    ),
    path(
        "editar-transacao/<int:pk>", EditarTransacao.as_view(), name="editar_transacao"
    ),
    path(
        "editar-agendamento/<int:pk>",
        EditarAgendamento.as_view(),
        name="editar_agendamento",
    ),
    path("excluir/<str:model_name>/<int:pk>", delete, name="excluir"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("clinica.urls")),
]

clinica/models.py
from django.db import models


# Create your models here.
class Paciente(models.Model):
    nome = models.CharField(max_length=100)
    idade = models.IntegerField()
    sexo = models.CharField(
        max_length=1, choices=[("M", "Masculino"), ("F", "Feminino")]
    )
    altura = models.DecimalField(max_digits=3, decimal_places=2)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Profissional(models.Model):
    nome = models.CharField(max_length=100)
    especialidade = models.CharField(max_length=100)
    registro_profissional = models.CharField(max_length=50, unique=True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nome} - {self.especialidade}"


class Transacao(models.Model):
    TIPO_TRANSACAO = [
        ("C", "Crédito"),
        ("D", "Débito"),
    ]

    paciente = models.ForeignKey(
        Paciente, on_delete=models.SET_NULL, null=True, blank=True
    )
    profissional = models.ForeignKey(
        Profissional, on_delete=models.SET_NULL, null=True, blank=True
    )
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    tipo = models.CharField(max_length=1, choices=TIPO_TRANSACAO)
    descricao = models.TextField(null=True, blank=True)
    data = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.get_tipo_display()} - {self.valor} - {self.data.strftime('%d/%m/%Y')}"


class Agendamento(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    profissional = models.ForeignKey(Profissional, on_delete=models.CASCADE)
    data_horario = models.DateTimeField()
    descricao = models.TextField(null=True, blank=True)
    confirmado = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Agendamento - {self.paciente.nome} com {self.profissional.nome} em {self.data_horario.strftime('%d/%m/%Y %H:%M')}"

clinica/forms.py
from django import forms
from .models import Paciente, Profissional, Transacao, Agendamento


class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = [
            "nome",
            "idade",
            "sexo",
            "altura",
            "peso",
        ]
        widgets = {
            "nome": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Nome do paciente"}
            ),
            "idade": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Idade do paciente"}
            ),
            "sexo": forms.Select(
                attrs={"class": "form-control", "placeholder": "Sexo do paciente"},
            ),
            "altura": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Altura do paciente"}
            ),
            "peso": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Peso do paciente"}
            ),
        }

    def clean_nome(self):
        nome = self.cleaned_data["nome"]
        if len(nome) < 3:
            raise forms.ValidationError("Nome deve ter mais de 3 caracteres")
        return nome

    def clean_idade(self):
        idade = self.cleaned_data["idade"]
        if idade < 0:
            raise forms.ValidationError("Idade não pode ser negativa")
        elif idade > 120:
            raise forms.ValidationError("Idade não pode ser maior que 120 anos")
        return idade

    def clean_altura(self):
        altura = self.cleaned_data["altura"]
        if altura < 0:
            raise forms.ValidationError("Altura não pode ser negativa")
        elif altura > 3:
            raise forms.ValidationError("Altura não pode ser maior que 3 metros")
        return altura

    def clean_peso(self):
        peso = self.cleaned_data["peso"]
        if peso < 0:
            raise forms.ValidationError("Peso não pode ser negativo")
        elif peso > 300:
            raise forms.ValidationError("Peso não pode ser maior que 300 kg")
        return peso


class ProfissionalForm(forms.ModelForm):
    class Meta:
        model = Profissional
        fields = [
            "nome",
            "especialidade",
            "registro_profissional",
        ]
        widgets = {
            "nome": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Nome do profissional"}
            ),
            "especialidade": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Especialidade do profissional",
                }
            ),
            "registro_profissional": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Registro profissional do profissional",
                }
            ),
        }

    def clean_nome(self):
        nome = self.cleaned_data["nome"]
        if len(nome) < 3:
            raise forms.ValidationError("Nome deve ter mais de 3 caracteres")
        return nome

    def clean_especialidade(self):
        especialidade = self.cleaned_data["especialidade"]
        if len(especialidade) < 3:
            raise forms.ValidationError("Especialidade deve ter mais de 3 caracteres")
        return especialidade

    def clean_registro_profissional(self):
        registro_profissional = self.cleaned_data["registro_profissional"]
        if len(registro_profissional) < 3:
            raise forms.ValidationError(
                "Registro profissional deve ter mais de 3 caracteres"
            )
        return registro_profissional


class TransacaoForm(forms.ModelForm):
    class Meta:
        model = Transacao
        fields = [
            "paciente",
            "profissional",
            "valor",
            "tipo",
            "descricao",
        ]
        widgets = {
            "paciente": forms.Select(
                attrs={"class": "form-control", "placeholder": "Paciente"}
            ),
            "profissional": forms.Select(
                attrs={"class": "form-control", "placeholder": "Profissional"}
            ),
            "valor": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Valor da transação"}
            ),
            "tipo": forms.Select(
                attrs={"class": "form-control", "placeholder": "Tipo da transação"},
            ),
            "descricao": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Descrição da transação"}
            ),
        }


class AgendamentoForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        fields = [
            "paciente",
            "profissional",
            "data_horario",
            "descricao",
            "confirmado",
        ]
        widgets = {
            "paciente": forms.Select(
                attrs={"class": "form-control", "placeholder": "Paciente"}
            ),
            "profissional": forms.Select(
                attrs={"class": "form-control", "placeholder": "Profissional"}
            ),
            "data_horario": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "type": "datetime-local",
                    "class": "form-control datetimepicker-input",
                },
            ),
            "descricao": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Descrição do agendamento",
                }
            ),
            "confirmado": forms.Select(
                choices=[(True, "Sim"), (False, "Não")],
                attrs={
                    "class": "form-control",
                    "placeholder": "Agendamento confirmado",
                },
            ),
        }

clinica/views.py
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView, ListView, UpdateView

from clinica.forms import PacienteForm, ProfissionalForm, TransacaoForm, AgendamentoForm
from clinica.models import Paciente, Profissional, Transacao, Agendamento


class Home(TemplateView):
    template_name = "index.html"


class ListarPacientes(ListView):
    template_name = "listar_pacientes.html"
    model = Paciente
    context_object_name = "pacientes"


class ListarProfissionais(ListView):
    template_name = "listar_profissionais.html"
    model = Profissional
    context_object_name = "profissionais"


class ListarTransacoes(ListView):
    template_name = "listar_transacoes.html"
    model = Transacao
    context_object_name = "transacoes"


class ListarAgendamentos(ListView):
    template_name = "listar_agendamentos.html"
    model = Agendamento
    context_object_name = "agendamentos"


class CadastrarPacientes(CreateView):
    template_name = "cadastrar_pacientes.html"
    model = Paciente
    form_class = PacienteForm
    success_url = "/"

    def form_valid(self, form):
        paciente = form.save(commit=True)
        return super().form_valid(form)


class CadastrarProfissionais(CreateView):
    template_name = "cadastrar_profissionais.html"
    model = Profissional
    form_class = ProfissionalForm
    success_url = "/"

    def form_valid(self, form):
        profissional = form.save(commit=True)
        return super().form_valid(form)


class CadastrarTransacoes(CreateView):
    template_name = "cadastrar_transacoes.html"
    model = Transacao
    form_class = TransacaoForm
    success_url = "/"

    def form_valid(self, form):
        transacao = form.save(commit=True)
        return super().form_valid(form)


class CadastrarAgendamentos(CreateView):
    template_name = "cadastrar_agendamentos.html"
    model = Agendamento
    form_class = AgendamentoForm
    success_url = "/"

    def form_valid(self, form):
        agendamento = form.save(commit=True)
        return super().form_valid(form)


class EditarPaciente(UpdateView):
    template_name = "editar.html"
    model = Paciente
    form_class = PacienteForm
    success_url = "/listar-pacientes"

    def form_valid(self, form):
        paciente = form.save(commit=True)
        return super().form_valid(form)


class EditarProfissional(UpdateView):
    template_name = "editar.html"
    model = Profissional
    form_class = ProfissionalForm
    success_url = "/listar-profissionais"

    def form_valid(self, form):
        profissional = form.save(commit=True)
        return super().form_valid(form)


class EditarTransacao(UpdateView):
    template_name = "editar.html"
    model = Transacao
    form_class = TransacaoForm
    success_url = "/listar-transacoes"

    def form_valid(self, form):
        transacao = form.save(commit=True)
        return super().form_valid(form)


class EditarAgendamento(UpdateView):
    template_name = "editar.html"
    model = Agendamento
    form_class = AgendamentoForm
    success_url = "/listar-agendamentos"

    def form_valid(self, form):
        agendamento = form.save(commit=True)
        return super().form_valid(form)


def delete(request, model_name, pk):
    model_map = {
        "paciente": Paciente,
        "profissional": Profissional,
        "transacao": Transacao,
        "agendamento": Agendamento,
    }

    model = model_map.get(model_name)
    if not model:
        raise Http404("Model not found")

    instance = model.objects.get(pk=pk)
    instance.delete()

    redirect_map = {
        "paciente": "clinica:listar_pacientes",
        "profissional": "clinica:listar_profissionais",
        "transacao": "clinica:listar_transacoes",
        "agendamento": "clinica:listar_agendamentos",
    }

    return redirect(redirect_map.get(model_name, "/"))

clinica/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Clínica Veloz</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  {% block stylesheets %}
  {% endblock %}
</head>
<body>
  <div class="container">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'clinica:home' %}">Clínica Veloz</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="cadastrarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Cadastrar
              </a>
              <ul class="dropdown-menu" aria-labelledby="cadastrarDropdown">
                <li><a class="dropdown-item" href="{% url 'clinica:cadastrar_pacientes' %}">Pacientes</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:cadastrar_profissionais' %}">Profissionais</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:cadastrar_transacoes' %}">Transações</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:cadastrar_agendamentos' %}">Agendamentos</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="listarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Listar
              </a>
              <ul class="dropdown-menu" aria-labelledby="listarDropdown">
                <li><a class="dropdown-item" href="{% url 'clinica:listar_pacientes' %}">Pacientes</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:listar_profissionais' %}">Profissionais</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:listar_transacoes' %}">Transações</a></li>
                <li><a class="dropdown-item" href="{% url 'clinica:listar_agendamentos' %}">Agendamentos</a></li>
              </ul>
            </li>
          </ul>
          <a class="btn btn-outline-primary" href="/admin">Admin Access</a>
        </div>
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  {% block scripts %}
  {% endblock %}
</body>
</html>

clinica/templates/cadastrar_agendamentos.html
{% extends "base.html" %}

{% block title %}Cadastrar Agendamentos{% endblock %}

{% block content %}
    <h1>Cadastrar Agendamentos</h1>
    {% include "_partials/form.html" %}
{% endblock %}

clinica/templates/cadastrar_pacientes.html
{% extends "base.html" %}

{% block title %}Cadastrar Pacientes{% endblock %}

{% block content %}
    <h1>Cadastrar Pacientes</h1>
    {% include "_partials/form.html" %}
{% endblock %}

clinica/templates/cadastrar_profissionais.html
{% extends "base.html" %}

{% block title %}Cadastrar Profissionais{% endblock %}

{% block content %}
    <h1>Cadastrar Profissionais</h1>
    {% include "_partials/form.html" %}
{% endblock %}

clinica/templates/cadastrar_transacoes.html
{% extends "base.html" %}

{% block title %}Cadastrar Transações{% endblock %}

{% block content %}
    <h1>Cadastrar Transações</h1>
    {% include "_partials/form.html" %}
{% endblock %}

clinica/templates/editar.html
{% extends 'base.html' %}

{% block title %}Editar{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Editar</h1>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
{% endblock %}

clinica/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <div class="jumbotron">
            <h1 class="display-4">Bem-vindo à Clínica Veloz</h1>
            <p class="lead">Sua saúde é nossa prioridade. Oferecemos serviços médicos de primeira linha para garantir seu bem-estar.</p>
            <hr class="my-4">
            <p>Explore nossos serviços e conheça mais sobre nós.</p>
            <a class="btn btn-primary btn-lg" href="#" role="button">Saiba mais</a>
        </div>
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">© 2024 Clínica Veloz. Todos os Direitos Reservados.</span>
        </div>
    </footer>
{% endblock %}

clinica/templates/listar_agendamentos.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Listar Agendamentos</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover rounded">
                <thead class="thead-dark">
                    <tr>
                        <th>Paciente</th>
                        <th>Profissional</th>
                        <th>Data e Hora</th>
                        <th>Descrição</th>
                        <th>Confirmado</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for agendamento in agendamentos %}
                        <tr>
                            <td>{{ agendamento.paciente }}</td>
                            <td>{{ agendamento.profissional }}</td>
                            <td>{{ agendamento.data_horario }}</td>
                            <td>{{ agendamento.descricao }}</td>
                            <td>{{ agendamento.confirmado }}</td>
                            <td>
                                <a href="{% url 'clinica:editar_agendamento' agendamento.id %}" class="btn btn-primary btn-sm rounded-pill">Editar</a>
                                <a href="{% url 'clinica:excluir' 'agendamento' agendamento.id %}" class="btn btn-danger btn-sm rounded-pill">Excluir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

clinica/templates/listar_pacientes.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Listar Pacientes</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover rounded">
                <thead class="thead-dark">
                    <tr>
                        <th>Nome</th>
                        <th>Idade</th>
                        <th>Sexo</th>
                        <th>Altura</th>
                        <th>Peso</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for paciente in pacientes %}
                        <tr>
                            <td>{{ paciente.nome }}</td>
                            <td>{{ paciente.idade }}</td>
                            <td>{{ paciente.sexo }}</td>
                            <td>{{ paciente.altura }}</td>
                            <td>{{ paciente.peso }}</td>
                            <td>
                                <a href="{% url 'clinica:editar_paciente' paciente.id %}" class="btn btn-primary btn-sm rounded-pill">Editar</a>
                                <a href="{% url 'clinica:excluir' 'paciente' paciente.id %}" class="btn btn-danger btn-sm rounded-pill">Excluir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

clinica/templates/listar_profissionais.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Listar Profissionais</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover rounded">
                <thead class="thead-dark">
                    <tr>
                        <th>Nome</th>
                        <th>Especialidade</th>
                        <th>Registro Profissional</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for profissional in profissionais %}
                        <tr>
                            <td>{{ profissional.nome }}</td>
                            <td>{{ profissional.especialidade }}</td>
                            <td>{{ profissional.registro_profissional }}</td>
                            <td>
                                <a href="{% url 'clinica:editar_profissional' profissional.id %}" class="btn btn-primary btn-sm rounded-pill">Editar</a>
                                <a href="{% url 'clinica:excluir' 'profissional' profissional.id %}" class="btn btn-danger btn-sm rounded-pill">Excluir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

clinica/templates/listar_transacoes.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Listar Transações</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover rounded">
                <thead class="thead-dark">
                    <tr>
                        <th>Paciente</th>
                        <th>Profissional</th>
                        <th>Valor</th>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transacao in transacoes %}
                        <tr>
                            <td>{{ transacao.paciente }}</td>
                            <td>{{ transacao.profissional }}</td>
                            <td>{{ transacao.valor }}</td>
                            <td>{{ transacao.tipo }}</td>
                            <td>{{ transacao.descricao }}</td>
                            <td>{{ transacao.data }}</td>
                            <td>
                                <a href="{% url 'clinica:editar_transacao' transacao.id %}" class="btn btn-primary btn-sm rounded-pill">Editar</a>
                                <a href="{% url 'clinica:excluir' 'transacao' transacao.id %}" class="btn btn-danger btn-sm rounded-pill">Excluir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}